# 도커 컴포즈의 버전
version: "3"
# 이곳에 실행하려는 컨테이너들을 정의
services:
  # 컨테이너 이름
  vue:
    # 현 디렉토리에 있는 Dockerfile 사용
    build:
      # 도커 이미지를 구성하기 위한 파일과 폴더들이 있는 위치
      context: .
      # 도커 파일 어떤 것인지 지정
      dockerfile: Dockerfile.dev
    # 포트 맵핑 로컬포트 : 컨테이너포트
    ports:
      - "8000:8080"
    # 로컬 머신에 있는 파일들 맵핑
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    #  vue 앱을 끌때 필요(버그 수정)
    stdin_open: true

  # docker-compose up
    # docker-compose up --build